-- MySQL Script generated by MySQL Workbench
-- 02/10/17 16:21:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ratepersons
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ratepersons` ;

-- -----------------------------------------------------
-- Schema ratepersons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ratepersons` DEFAULT CHARACTER SET utf8 ;
USE `ratepersons` ;

-- -----------------------------------------------------
-- Table `ratepersons`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`roles` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`roles` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`users` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`users` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(75) NOT NULL,
  `Login` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `AdminID` INT(11) NOT NULL,
  `RoleID` INT(11) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  INDEX `FK_users_adminid` (`AdminID` ASC),
  INDEX `FK_roles_users_idx` (`RoleID` ASC),
  CONSTRAINT `FK_roles_users`
    FOREIGN KEY (`RoleID`)
    REFERENCES `ratepersons`.`roles` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_users_adminid`
    FOREIGN KEY (`AdminID`)
    REFERENCES `ratepersons`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`persons` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`persons` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1024) NOT NULL,
  `AdminID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `FK_users_persons_idx` (`AdminID` ASC),
  CONSTRAINT `FK_users_persons`
    FOREIGN KEY (`AdminID`)
    REFERENCES `ratepersons`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`keywords` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`keywords` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1024) NOT NULL,
  `PersonID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `FK_Persons_idx` (`PersonID` ASC),
  CONSTRAINT `FK_persons_keywords`
    FOREIGN KEY (`PersonID`)
    REFERENCES `ratepersons`.`persons` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`sites` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`sites` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1024) NOT NULL,
  `AdminID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `FK_users_sites_idx` (`AdminID` ASC),
  CONSTRAINT `FK_users_sites`
    FOREIGN KEY (`AdminID`)
    REFERENCES `ratepersons`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`pages` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`pages` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(2048) NOT NULL,
  `SiteID` INT(11) NOT NULL,
  `FoundDateTime` DATETIME NULL DEFAULT NULL,
  `LastScanDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_sites_pages` (`SiteID` ASC),
  CONSTRAINT `FK_sites_pages`
    FOREIGN KEY (`SiteID`)
    REFERENCES `ratepersons`.`sites` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ratepersons`.`personpagerank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratepersons`.`personpagerank` ;

CREATE TABLE IF NOT EXISTS `ratepersons`.`personpagerank` (
  `PersonID` INT(11) NOT NULL,
  `PageID` INT(11) NOT NULL,
  `Rank` INT(11) NOT NULL,
  INDEX `FK_persons_idx` (`PersonID` ASC),
  INDEX `FK_pages_idx` (`PageID` ASC),
  CONSTRAINT `FK_pages_personpagerank`
    FOREIGN KEY (`PageID`)
    REFERENCES `ratepersons`.`pages` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_persons_personpagerank`
    FOREIGN KEY (`PersonID`)
    REFERENCES `ratepersons`.`persons` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
